on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        default: sandbox
      tag:
        required: true
        type: string
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Start new docker container
        run: |
          echo "I'm a command from reusable workflow"
          echo "Here should be deployment steps"
          echo "Deploying ${{ inputs.tag }} to ${{ inputs.environment }}"
