name: Reusable deployment workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string
        description: "env"
        default: sandbox
      tag:
        required: true
        description: tag
        type: string
jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-22.04
    environment: ${{ inputs.environment }}
    steps:
      - name: Start new docker container
        run: |
          echo "I'm a command from reusable workflow"
          echo "Here should be deployment steps"
          echo "Deploying ${{ inputs.tag }} to ${{ inputs.environment }}"
          echo -n "${{ secrets.ENV_NAME }}" | xxd -ps
