name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@v9.1.0
        with:
          tag-prefix: 'v'
#          tag-suffix: (endsWith(github.ref, 'dev') && '-dev') || ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo ${{ steps.version-bump.outputs.newTag }}
      - name: Publish release
        if: github.ref_type == 'branch' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: ${{ steps.version-bump.outputs.newTag }}
          tag_name: ${{ steps.version-bump.outputs.newTag }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: release-flow:${{ steps.version-bump.outputs.newTag }}
#
#  deploy:
#    name: deploy
#    uses: sturman/release-flow/.github/workflows/install-chromium.yaml@main
#    needs:
#      - release
#    with:
#      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'sandbox' }}
#      tag: ${{ needs.release.outputs.tag }}
