name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.version.outputs.IMAGE_TAG }}
    steps:
      - uses: actions/checkout@v3
      - name: Define version
        id: version
        run: |
          APP_VERSION=$(cat package.json | jq -r '.version')${{ (endsWith(github.ref, 'dev') && '-dev') || '' }}
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${APP_VERSION}" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=${APP_VERSION}" >> $GITHUB_ENV
      - name: Publish release
        if: github.ref_type == 'branch' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: Release ${{ env.APP_VERSION }}
          tag_name: ${{ env.APP_VERSION }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: release-flow:${{ env.IMAGE_TAG }}
#
#  deploy:
#    name: deploy
#    uses: sturman/release-flow/.github/workflows/deploy.yaml@main
#    needs:
#      - release
#    with:
#      environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'sandbox' }}
#      tag: ${{ needs.release.outputs.tag }}
