name: Release

on:
  workflow_dispatch:
    inputs:
      version_type:
        type: choice
        default: patch
        required: true
        description: Bump version type
        options:
          - patch
          - minor
          - major

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Version Bump
        id: version-bump
        uses: 'phips28/gh-action-bump-version@v9.1.3'
        with:
          tag-prefix: 'v'
          version-type: ${{ github.event.inputs.version_type }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Output Step'
        run: echo "New tag ${{ steps.version-bump.outputs.newTag }}"
      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: Release ${{ steps.version-bump.outputs.newTag }}
          tag_name: ${{ steps.version-bump.outputs.newTag }}
      - name: Define release image tag
        run: |
          # v1.2.3
          echo "IMAGE_TAG=${{ steps.version-bump.outputs.newTag }}"
          echo "IMAGE_TAG=${{ steps.version-bump.outputs.newTag }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: release-flow:\$IMAGE_TAG
