name: Release

on:
  push:
    branches:
      - main
      - dev

jobs:
  release:
    name: release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Define version
        run: |
          APP_VERSION=$(cat package.json | jq -r '.version')${{ (endsWith(github.ref, 'dev') && '-dev') || '' }}
          echo "APP_VERSION=${APP_VERSION}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ env.APP_VERSION }}" >> $GITHUB_ENV
      - name: Publish dev release
        if: github.ref_type == 'branch' && github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: Release ${{ env.APP_VERSION }}
          tag_name: ${{ env.APP_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-west-1
          role-to-assume: arn:aws:iam::506215618020:role/frt-github-actions
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container image
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: release-flow:${{ env.IMAGE_TAG }}
